### ISSUE TITLE
Servers not loading

### ISSUE THREAD

**Issue by Sologolos** [flathub/net.brinkervii.grapejuice#114] opened 2023-09-02 22:21 UTC
Could you make it so that the servers will load please

**Comment by guihkx** [comment] 2023-09-02 22:39
Did you install Gecko when prompted by Wine?

Also, a screenshot showing what your problem looks like would probably help.

**Comment by Sologolos** [comment] 2023-09-03 08:42
![Polish_20230903_094059888](https://github.com/flathub/net.brinkervii.grapejuice/assets/143910612/8dd5ca3d-959a-4f86-8c29-6ae44da3693e)
Thats what happens when i open up servers for any game, and i think i did install gecko, can you explain how to just to check that i did

**Comment by guihkx** [comment] 2023-09-03 14:32
Oh, I thought you were talking about something else. 

Unfortunately, I'm afraid this can only be fixed in Wine:

https://gitlab.com/brinkervii/grapejuice/-/issues/423#note_1294023501

**Comment by lunarlattice0** [comment] 2023-09-04 06:21
Unfortunately, guihkx is correct, this is not a bug we can fix.

**Closed as completed by lunarlattice0** 2023-09-04 06:21 UTC
